env:
  browser: true
  node: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - prettier
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
  - import
rules:
  vue/multi-word-component-names: off
  import/no-unresolved: off
  sort-imports: off
  import/order: ["error", { alphabetize: { order: "asc" } }]
