name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          corepack enable
          pnpm -v
          node -v
          pnpm i
      - name: Lint
        run: |
          pnpm run lint
          pnpm run format
      - name: Unit test
        run: pnpm run test
      - name: Build
        run: pnpm run build
