name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: |
          corepack enable
          pnpm -v
          node -v
          pnpm i
      - name: Lint
        run: |
          pnpm run lint
          pnpm run format
      - name: Unit test
        run: pnpm run test
      - name: Build
        run: pnpm run build
